'use strict';
module.exports = function(sequelize, DataTypes) {
  var Listing = sequelize.define('Listing', {
      listing_id: {type: DataTypes.INTEGER, allowNull: false, primaryKey: true},
      listing_url: { type: DataTypes.TEXT }, 
      scrape_id: {     type: DataTypes.INTEGER },   
      last_scraped : {     type: DataTypes.DATE  },
      name :{ type: DataTypes.TEXT  }, 
      summary :{     type: DataTypes.TEXT  },
      space1 : {     type: DataTypes.TEXT  }, 
      description: {     type: DataTypes.TEXT  }, 
      experiences_offered :{     type: DataTypes.TEXT  }, 
      neighborhood_overview :{     type: DataTypes.TEXT  }, 
      notes :{     type: DataTypes.TEXT  }, 
      transit: {     type: DataTypes.TEXT  }, 
      access: {     type: DataTypes.TEXT  }, 
      interaction :{     type: DataTypes.TEXT  }, 
      house_rules :{     type: DataTypes.TEXT  }, 
      thumbnail_url: {     type: DataTypes.TEXT  },
      medium_url: {     type: DataTypes.TEXT  }, 
      picture_url: {     type: DataTypes.TEXT  }, 
      xl_picture_url : {     type: DataTypes.TEXT  }, 
      host_id: {     type: DataTypes.DOUBLE  }, 
      host_url: {     type: DataTypes.TEXT  }, 
      host_name: {     type: DataTypes.TEXT  }, 
      host_since: {     type: DataTypes.DATE  }, 
      host_location: {     type: DataTypes.TEXT  }, 
      host_about:{     type: DataTypes.TEXT  }, 
      host_response_time: {     type: DataTypes.TEXT  }, 
      host_response_rate: {     type: DataTypes.TEXT  }, 
      host_acceptance_rate: {     type: DataTypes.TEXT  },  
      host_is_superhost:{     type: DataTypes.TEXT  },   
      host_thumbnail_url :{     type: DataTypes.TEXT  },  
      host_picture_url :{     type: DataTypes.TEXT  },   
      host_neighbourhood :{     type: DataTypes.TEXT  },  
      host_listings_count :{     type: DataTypes.DOUBLE  },   
      host_total_listings_count :{     type: DataTypes.DOUBLE  },   
      host_verifications :{     type: DataTypes.TEXT  },  
      host_has_profile_pic :{     type: DataTypes.TEXT  },   
      host_identity_verified:{     type: DataTypes.TEXT  },    
      street :{     type: DataTypes.TEXT  },   
      neighbourhood :{     type: DataTypes.TEXT  },   
      neighbourhood_cleansed :{     type: DataTypes.TEXT  },  
      neighbourhood_group_cleansed:{     type: DataTypes.TEXT  },    
      city:{     type: DataTypes.TEXT  },    
      state :{     type: DataTypes.TEXT  },  
      zipcode :{     type: DataTypes.DOUBLE  },   
      market :{     type: DataTypes.TEXT  },   
      smart_location :{     type: DataTypes.TEXT  },  
      country_code :{     type: DataTypes.TEXT  },   
      country:{     type: DataTypes.TEXT  },    
      latitude :{     type: DataTypes.DOUBLE  },   
      longitude :{     type: DataTypes.DOUBLE  },   
      is_location_exact :{     type: DataTypes.TEXT  },   
      property_type :{     type: DataTypes.TEXT  },  
      room_type :{     type: DataTypes.TEXT  }, 
      accommodates :{     type: DataTypes.DOUBLE  },   
      bathrooms :{     type: DataTypes.DOUBLE  },   
      bedrooms:{     type: DataTypes.DOUBLE  },   
      beds :{     type: DataTypes.DOUBLE  },   
      bed_type :{     type: DataTypes.TEXT  },   
      amenities :{     type: DataTypes.TEXT  },  
      square_feet:{     type: DataTypes.DOUBLE  },    
      price :{     type: DataTypes.DECIMAL(10,0)  },   
      weekly_price :{     type: DataTypes.DECIMAL(10,0)  },   
      monthly_price :{     type: DataTypes.DECIMAL(10,0)  },  
      security_deposit:{     type: DataTypes.DECIMAL(10,0)  },    
      cleaning_fee :{     type: DataTypes.DECIMAL(10,0)  },   
      guests_included :{    type: DataTypes.DOUBLE  },   
      extra_people :{     type: DataTypes.DECIMAL(10,0)  },   
      minimum_nights:{     type: DataTypes.TEXT  },   
      maximum_nights :{     type: DataTypes.DOUBLE  },   
      calendar_updated :{     type: DataTypes.DATE  },   
      has_availability :{     type: DataTypes.TEXT  },   
      availability_30 :{     type: DataTypes.DOUBLE  },   
      availability_60 :{     type: DataTypes.DOUBLE  },   
      availability_90 :{     type: DataTypes.DOUBLE  },   
      availability_365 :{     type: DataTypes.DOUBLE  },   
      calendar_last_scraped:{     type: DataTypes.DATE  },   
      number_of_reviews :{     type: DataTypes.DOUBLE  },   
      first_review :{     type: DataTypes.DATE  },   
      last_review :{     type: DataTypes.DATE  },   
      review_scores_rating :{     type: DataTypes.DOUBLE  },   
      review_scores_accuracy :{     type: DataTypes.DOUBLE  },   
      review_scores_cleanliness:{     type: DataTypes.DOUBLE  },    
      review_scores_checkin:{     type: DataTypes.DOUBLE  },   
      review_scores_communication :{     type: DataTypes.DOUBLE  },  
      review_scores_location:{     type: DataTypes.DOUBLE  },   
      review_scores_value :{     type: DataTypes.DOUBLE  },  
      requires_license :{     type: DataTypes.TEXT  },   
      license :{     type: DataTypes.TEXT  },   
      jurisdiction_names :{     type: DataTypes.TEXT  },   
      instant_bookable :{     type: DataTypes.TEXT  },   
      cancellation_policy :{     type: DataTypes.TEXT  },   
      require_guest_profile_picture:{     type: DataTypes.TEXT  },   
      require_guest_phone_verification:{     type: DataTypes.TEXT  },   
      calculated_host_listings_count :{     type: DataTypes.DOUBLE  },  
      reviews_per_month :{     type: DataTypes.TEXT  },   
      price_num :{     type: DataTypes.DECIMAL(10,0)  },   
      weekly_price_num :{     type: DataTypes.DECIMAL(10,0)  },    
      monthly_price_num :{     type: DataTypes.DECIMAL(10,0)  },   
      security_deposit_num :{     type: DataTypes.DECIMAL(10,0) }
},
{
    classMethods: {
      associate: function(models) {
        // associations can be defined here
          Listing.hasMany(Calendar,  {as: 'Workers'});
      }
    }
  });
  return Listing;
};